name: Build

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    name: Cache dependencies
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache pip dependencies
        id: cache-pip-deps
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

  test1:
    needs: [build]
    name: pytest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Print cache contents
        run: ls -l ~/.cache/pip

      - name: Restore pip dependencies cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Print cache contents after restore
        run: ls -l ~/.cache/pip
    
      - name: Install cached dependencies
        run: pip install -r requirements.txt


  
